name: rolebase
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  firebase_storage: ^12.0.0
  flutter_animation_progress_bar: ^2.3.1
  cross_file: ^0.3.4+1
  google_fonts: ^6.2.1
  ionicons: ^0.2.2
  provider: ^6.1.1
  flutter_svg: ^2.0.9 
  firebase_database: ^11.0.0
  file_picker: ^8.0.4
  google_maps_flutter: ^2.7.0
  http: ^1.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.0.8
  flutter_local_notifications: ^17.2.1+2
  table_calendar: ^3.1.2
  timezone: ^0.9.1
  cached_network_image: ^3.2.0
  video_player: ^2.6.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
assets: 
- assets/