// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnTXEVxkeFY6Fq-QlQeJ_QyuqW5z38R24',
    appId: '1:771910466977:web:6a17ea938cc8f7f7141fe0',
    messagingSenderId: '771910466977',
    projectId: 'rolebased-6c443',
    authDomain: 'rolebased-6c443.firebaseapp.com',
    databaseURL: 'https://rolebased-6c443-default-rtdb.firebaseio.com',
    storageBucket: 'rolebased-6c443.appspot.com',
    measurementId: 'G-TZNR7K17KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkcjC9F9dyqWSvPa9tH10Hmn4MhaUZzV8',
    appId: '1:771910466977:android:78da025cdd4088ef141fe0',
    messagingSenderId: '771910466977',
    projectId: 'rolebased-6c443',
    databaseURL: 'https://rolebased-6c443-default-rtdb.firebaseio.com',
    storageBucket: 'rolebased-6c443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzBUt-y9AuAapbw9gs_mAX9_NQUk2b1qI',
    appId: '1:771910466977:ios:e5be8910dcc31ee4141fe0',
    messagingSenderId: '771910466977',
    projectId: 'rolebased-6c443',
    databaseURL: 'https://rolebased-6c443-default-rtdb.firebaseio.com',
    storageBucket: 'rolebased-6c443.appspot.com',
    androidClientId: '771910466977-bngjnch4v13aopnt2cg3hn7cbcl8a05a.apps.googleusercontent.com',
    iosClientId: '771910466977-0j237arni97qa0u64puentv830jnr8bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.rolebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzBUt-y9AuAapbw9gs_mAX9_NQUk2b1qI',
    appId: '1:771910466977:ios:e5be8910dcc31ee4141fe0',
    messagingSenderId: '771910466977',
    projectId: 'rolebased-6c443',
    databaseURL: 'https://rolebased-6c443-default-rtdb.firebaseio.com',
    storageBucket: 'rolebased-6c443.appspot.com',
    androidClientId: '771910466977-bngjnch4v13aopnt2cg3hn7cbcl8a05a.apps.googleusercontent.com',
    iosClientId: '771910466977-0j237arni97qa0u64puentv830jnr8bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.rolebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnTXEVxkeFY6Fq-QlQeJ_QyuqW5z38R24',
    appId: '1:771910466977:web:94657260a1d60e79141fe0',
    messagingSenderId: '771910466977',
    projectId: 'rolebased-6c443',
    authDomain: 'rolebased-6c443.firebaseapp.com',
    databaseURL: 'https://rolebased-6c443-default-rtdb.firebaseio.com',
    storageBucket: 'rolebased-6c443.appspot.com',
    measurementId: 'G-S6KJV5ZJ17',
  );

}